# Two targets, one base:
#   test     — adds the dev requirements and the test suite (CI, local runs)
#   runtime  — the ingest image: runtime requirements and src/ only (default)
#
# The row contract is NOT copied in. It is generated by platform/schemas and
# mounted at runtime (SCHEMA_DIR), so the image never carries a second copy that
# could disagree with the contract the warehouse was built from.

FROM python:3.12-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app


FROM base AS test
COPY requirements.txt requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt
COPY pyproject.toml ./
COPY src ./src
COPY tests ./tests
CMD ["pytest"]


FROM base AS runtime
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY pyproject.toml ./
COPY src ./src

# Non-root, with the two writable mounts the service needs: the ingest ledger
# and the dead-letter queue. Both default under /state.
RUN useradd --create-home --uid 10001 indexer \
    && mkdir -p /state /schemas \
    && chown -R indexer:indexer /state
USER indexer

ENV PYTHONPATH=/app/src \
    STATE_DIR=/state \
    DLQ_DIR=/state/dlq \
    SCHEMA_DIR=/schemas/generated/arrow

ENTRYPOINT ["python", "src/__main__.py"]
CMD ["run"]
